/-
Copyright (c) 2026 CompElliptic Contributors.
Released under the Apache License, Version 2.0, or the MIT license, at your option,
as described in the files LICENSE-APACHE and LICENSE-MIT.
Authors: Daira-Emma Hopwood
-/
import CompElliptic.Asm.AArch64.PastaMul
import Mathlib.Data.Nat.ModEq
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.ClearExcept

/-!
# Correctness of the transcribed Pasta Montgomery routines

Each theorem here is proved over the transcription in `PastaMul.lean`, instruction by
instruction. The proof of a routine begins by unfolding it and extracting its `let`s under
unique names; then, for every instruction, the defining equation of its result (by `rfl`, in
`%`/`/` form) and its range are recorded and the local's value is cleared, so that each
`omega` call sees one carry step. Those lines are generated by
`scripts/gen_aarch64_pasta_mul.py --skeleton <routine>` and must not be edited; the
hand-written parts are the theorem statements and the `-- BEGIN ... -- END` blocks, which
state the Montgomery round invariants where they hold. `scripts/check_aarch64_pasta_mul.sh`
strips the blocks and checks that what remains is the current skeleton.

The moduli are assumed in the shape the code hard-codes: limbs `[p0, p1, 0, 2^62]`, with
`inv * p0 ≡ -1 (mod 2^64)`.
-/

namespace CompElliptic.Asm.AArch64

-- BEGIN cancel_low
/-- The Montgomery cancellation: with `inv * p0 ≡ -1 (mod 2^64)` and `q = inv * t0 mod 2^64`, the
low limb of `t0 + p0 * q` is zero. -/
theorem cancel_low (t0 inv p0 : Nat) (h : (inv * p0 + 1) % 2^64 = 0) :
    (t0 + p0 * (inv * t0 % 2^64) % 2^64) % 2^64 = 0 := by
  have key : (t0 + p0 * (inv * t0)) % 2^64 = 0 := by
    have : t0 + p0 * (inv * t0) = t0 * (inv * p0 + 1) := by ring
    rw [this, Nat.mul_mod, h]; simp
  have h1 : inv * t0 % 2^64 ≡ inv * t0 [MOD 2^64] := Nat.mod_modEq _ _
  have h2 : p0 * (inv * t0 % 2^64) % 2^64 ≡ p0 * (inv * t0) [MOD 2^64] :=
    (Nat.mod_modEq _ _).trans (Nat.ModEq.mul_left p0 h1)
  have h3 : t0 + p0 * (inv * t0 % 2^64) % 2^64 ≡ t0 + p0 * (inv * t0) [MOD 2^64] :=
    Nat.ModEq.add_left t0 h2
  exact Eq.trans h3 key
-- END cancel_low

-- BEGIN mulBy1_spec statement
/-- The shared reduction helper computes `(t + Q * p) / 2^256` for some `Q < 2^256`, with the
result in range, for any four-limb `t`. Since `Q < 2^256`, the result is congruent to
`t * 2^-256` modulo `p` and is below `p + t / 2^256 < p + 1`. -/
theorem mulBy1_spec (t modulus : Limbs) (inv : Nat) (ht : t.Bounded) (hm : modulus.Bounded)
    (hshape : modulus.l2 = 0 ∧ modulus.l3 = 2^62)
    (hinv_lt : inv < 2^64) (hinv : (inv * modulus.l0 + 1) % 2^64 = 0) :
    ∀ r, r = mulBy1 t modulus inv →
      r.Bounded ∧ ∃ Q, Q < 2^256 ∧ 2^256 * r.toNat = t.toNat + Q * modulus.toNat := by
  intro r hr
-- END mulBy1_spec statement
  -- generated skeleton for `mulBy1`: do not edit between the annotations
  unfold mulBy1 at hr
  lift_lets at hr
  extract_lets x10 x11 x12 x13 x4 x3 x5 x6 x15 x17 c x14 s x11_1 c_1 x15_1 s_1 x12_1 c_2 s_2 x13_1
      c_3 x17_1 x9 s_3 x10_1 c_4 s_4 x11_2 c_5 s_5 x12_2 c_6 x3_1 x13_2 x15_2 x17_2 c_7 x14_1 s_6
      x11_3 c_8 x15_3 s_7 x12_3 c_9 s_8 x13_3 c_10 x17_3 x9_1 s_9 x10_2 c_11 s_10 x11_4 c_12 s_11
      x12_4 c_13 x3_2 x13_4 x15_4 x17_4 c_14 x14_2 s_12 x11_5 c_15 x15_5 s_13 x12_5 c_16 s_14 x13_5
      c_17 x17_5 x9_2 s_15 x10_3 c_18 s_16 x11_6 c_19 s_17 x12_6 c_20 x3_3 x13_6 x15_6 x17_6 c_21
      x14_3 s_18 x11_7 c_22 x15_7 s_19 x12_7 c_23 s_20 x13_7 c_24 x17_7 x9_3 s_21 x10_4 c_25 s_22
      x11_8 c_26 s_23 x12_8 c_27 x13_8 at hr
  subst hr
  have e_x10 : x10 = t.l0 := rfl
  have b_x10 : x10 < 2^64 := by rw [e_x10]; exact ht.1
  clear_value x10
  have e_x11 : x11 = t.l1 := rfl
  have b_x11 : x11 < 2^64 := by rw [e_x11]; exact ht.2.1
  clear_value x11
  have e_x12 : x12 = t.l2 := rfl
  have b_x12 : x12 < 2^64 := by rw [e_x12]; exact ht.2.2.1
  clear_value x12
  have e_x13 : x13 = t.l3 := rfl
  have b_x13 : x13 < 2^64 := by rw [e_x13]; exact ht.2.2.2
  clear_value x13
  have e_x4 : x4 = inv := rfl
  have b_x4 : x4 < 2^64 := by rw [e_x4]; exact hinv_lt
  clear_value x4
  have e_x3 : x3 = x4 * x10 % 2^64 := rfl
  have b_x3 : x3 < 2^64 := by omega
  clear_value x3
  have e_x5 : x5 = modulus.l0 := rfl
  have b_x5 : x5 < 2^64 := by rw [e_x5]; exact hm.1
  clear_value x5
  have e_x6 : x6 = modulus.l1 := rfl
  have b_x6 : x6 < 2^64 := by rw [e_x6]; exact hm.2.1
  clear_value x6
  have e_x15 : x15 = x6 * x3 % 2^64 := rfl
  have b_x15 : x15 < 2^64 := by omega
  clear_value x15
  have e_x17 : x17 = x3 * 2^62 % 2^64 := rfl
  have b_x17 : x17 < 2^64 := by omega
  clear_value x17
  have e_c : c = (x10 + 2^64 - 1 - (1 - 1)) / 2^64 := rfl
  have l_c : (c = 1 ∧ 1 + 1 ≤ x10 + 1) ∨ (c = 0 ∧ x10 + 1 < 1 + 1) := by
    omega
  clear e_c
  clear_value c
  have p_x14 : x5 * x3 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x5 b_x3) (by norm_num)
  have e_x14 : x14 = x5 * x3 / 2^64 := rfl
  have b_x14 : x14 < 2^64 := by omega
  obtain ⟨lo_x14, b_lo_x14, d_x14⟩ :
      ∃ lo, lo < 2^64 ∧ lo + 2^64 * x14 = x5 * x3 :=
    ⟨x5 * x3 % 2^64, by omega, by omega⟩
  clear e_x14
  clear_value x14
  have e_x11_1 : x11_1 = (x11 + x15 + c) % 2^64 := rfl
  have e_c_1 : c_1 = (x11 + x15 + c) / 2^64 := rfl
  have l_x11_1 : x11_1 + 2^64 * c_1 = x11 + x15 + c := by omega
  have b_x11_1 : x11_1 < 2^64 := by omega
  have b_c_1 : c_1 ≤ 1 := by omega
  clear e_x11_1 e_c_1
  clear_value s x11_1 c_1
  have p_x15_1 : x6 * x3 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x6 b_x3) (by norm_num)
  have e_x15_1 : x15_1 = x6 * x3 / 2^64 := rfl
  have b_x15_1 : x15_1 < 2^64 := by omega
  have d_x15_1 : x15 + 2^64 * x15_1 = x6 * x3 := by omega
  clear e_x15 e_x15_1
  clear_value x15_1
  have e_x12_1 : x12_1 = (x12 + 0 + c_1) % 2^64 := rfl
  have e_c_2 : c_2 = (x12 + 0 + c_1) / 2^64 := rfl
  have l_x12_1 : x12_1 + 2^64 * c_2 = x12 + 0 + c_1 := by omega
  have b_x12_1 : x12_1 < 2^64 := by omega
  have b_c_2 : c_2 ≤ 1 := by omega
  clear e_x12_1 e_c_2
  clear_value s_1 x12_1 c_2
  have e_x13_1 : x13_1 = (x13 + x17 + c_2) % 2^64 := rfl
  have e_c_3 : c_3 = (x13 + x17 + c_2) / 2^64 := rfl
  have l_x13_1 : x13_1 + 2^64 * c_3 = x13 + x17 + c_2 := by omega
  have b_x13_1 : x13_1 < 2^64 := by omega
  have b_c_3 : c_3 ≤ 1 := by omega
  clear e_x13_1 e_c_3
  clear_value s_2 x13_1 c_3
  have e_x17_1 : x17_1 = x3 / 2^2 := rfl
  have b_x17_1 : x17_1 < 2^62 := by omega
  have sh_x17_1 : x17 + 2^64 * x17_1 = x3 * 2^62 := by omega
  clear e_x17 e_x17_1
  clear_value x17_1
  have e_x9 : x9 = (0 + 0 + c_3) % 2^64 := rfl
  have b_x9 : x9 < 2^64 := by omega
  obtain ⟨k_x9, b_k_x9, l_x9⟩ :
      ∃ k, k ≤ 1 ∧ x9 + 2^64 * k = 0 + 0 + c_3 :=
    ⟨(0 + 0 + c_3) / 2^64, by omega, by omega⟩
  clear e_x9
  clear_value x9
  have e_x10_1 : x10_1 = (x11_1 + x14 + 0) % 2^64 := rfl
  have e_c_4 : c_4 = (x11_1 + x14 + 0) / 2^64 := rfl
  have l_x10_1 : x10_1 + 2^64 * c_4 = x11_1 + x14 + 0 := by omega
  have b_x10_1 : x10_1 < 2^64 := by omega
  have b_c_4 : c_4 ≤ 1 := by omega
  clear e_x10_1 e_c_4
  clear_value s_3 x10_1 c_4
  have e_x11_2 : x11_2 = (x12_1 + x15_1 + c_4) % 2^64 := rfl
  have e_c_5 : c_5 = (x12_1 + x15_1 + c_4) / 2^64 := rfl
  have l_x11_2 : x11_2 + 2^64 * c_5 = x12_1 + x15_1 + c_4 := by omega
  have b_x11_2 : x11_2 < 2^64 := by omega
  have b_c_5 : c_5 ≤ 1 := by omega
  clear e_x11_2 e_c_5
  clear_value s_4 x11_2 c_5
  have e_x12_2 : x12_2 = (x13_1 + 0 + c_5) % 2^64 := rfl
  have e_c_6 : c_6 = (x13_1 + 0 + c_5) / 2^64 := rfl
  have l_x12_2 : x12_2 + 2^64 * c_6 = x13_1 + 0 + c_5 := by omega
  have b_x12_2 : x12_2 < 2^64 := by omega
  have b_c_6 : c_6 ≤ 1 := by omega
  clear e_x12_2 e_c_6
  clear_value s_5 x12_2 c_6
  have e_x3_1 : x3_1 = x4 * x10_1 % 2^64 := rfl
  have b_x3_1 : x3_1 < 2^64 := by omega
  clear_value x3_1
  have e_x13_2 : x13_2 = (x9 + x17_1 + c_6) % 2^64 := rfl
  have b_x13_2 : x13_2 < 2^64 := by omega
  obtain ⟨k_x13_2, b_k_x13_2, l_x13_2⟩ :
      ∃ k, k ≤ 1 ∧ x13_2 + 2^64 * k = x9 + x17_1 + c_6 :=
    ⟨(x9 + x17_1 + c_6) / 2^64, by omega, by omega⟩
  clear e_x13_2
  clear_value x13_2
  -- BEGIN round 0
  -- Cancellation: the low limb of `x10 + p0 * x3` is zero, so `x10 + lo_x14` is
  -- `0` or `2^64`, and `subs xzr, x10, #1` set the carry exactly when it is `2^64`.
  have hc_0 : x10 + lo_x14 = 2^64 * c := by
    have h := cancel_low x10 inv modulus.l0 hinv
    rw [← e_x5, ← e_x4, ← e_x3, ← d_x14, Nat.add_mul_mod_self_left,
      Nat.mod_eq_of_lt b_lo_x14] at h
    clear * - h b_x10 b_lo_x14 l_c
    omega
  -- Neither `adc` wraps: the fifth limb is at most `1`, and the shifted quotient is below
  -- `2^62`.
  have hk_0 : k_x9 = 0 ∧ k_x13_2 = 0 := by
    clear * - l_x9 b_c_3 l_x13_2 b_x17_1 b_c_6
    omega
  -- The round invariant is a linear combination of the instruction equations.
  have I_0 : 2^64 * (x10_1 + 2^64 * x11_2 + 2^128 * x12_2 + 2^192 * x13_2)
      = (x10 + 2^64 * x11 + 2^128 * x12 + 2^192 * x13)
        + (x5 * x3 + 2^64 * (x6 * x3) + 2^254 * x3) := by
    clear * - hc_0 d_x14 d_x15_1 l_x11_1 l_x12_1 l_x13_1 l_x10_1 l_x11_2 l_x12_2 sh_x17_1 l_x9
        l_x13_2 hk_0
    omega
  clear * - ht hm hshape hinv hinv_lt e_x4 e_x5 e_x6 b_x4 b_x5 b_x6 e_x10 e_x11 e_x12 e_x13 I_0
      b_x10_1 b_x11_2 b_x12_2 b_x13_2 b_x3 b_x3_1 e_x3_1
  -- END round 0
  have e_x15_2 : x15_2 = x6 * x3_1 % 2^64 := rfl
  have b_x15_2 : x15_2 < 2^64 := by omega
  clear_value x15_2
  have e_x17_2 : x17_2 = x3_1 * 2^62 % 2^64 := rfl
  have b_x17_2 : x17_2 < 2^64 := by omega
  clear_value x17_2
  have e_c_7 : c_7 = (x10_1 + 2^64 - 1 - (1 - 1)) / 2^64 := rfl
  have l_c_7 : (c_7 = 1 ∧ 1 + 1 ≤ x10_1 + 1) ∨ (c_7 = 0 ∧ x10_1 + 1 < 1 + 1) := by
    omega
  clear e_c_7
  clear_value c_7
  have p_x14_1 : x5 * x3_1 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x5 b_x3_1) (by norm_num)
  have e_x14_1 : x14_1 = x5 * x3_1 / 2^64 := rfl
  have b_x14_1 : x14_1 < 2^64 := by omega
  obtain ⟨lo_x14_1, b_lo_x14_1, d_x14_1⟩ :
      ∃ lo, lo < 2^64 ∧ lo + 2^64 * x14_1 = x5 * x3_1 :=
    ⟨x5 * x3_1 % 2^64, by omega, by omega⟩
  clear e_x14_1
  clear_value x14_1
  have e_x11_3 : x11_3 = (x11_2 + x15_2 + c_7) % 2^64 := rfl
  have e_c_8 : c_8 = (x11_2 + x15_2 + c_7) / 2^64 := rfl
  have l_x11_3 : x11_3 + 2^64 * c_8 = x11_2 + x15_2 + c_7 := by omega
  have b_x11_3 : x11_3 < 2^64 := by omega
  have b_c_8 : c_8 ≤ 1 := by omega
  clear e_x11_3 e_c_8
  clear_value s_6 x11_3 c_8
  have p_x15_3 : x6 * x3_1 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x6 b_x3_1) (by norm_num)
  have e_x15_3 : x15_3 = x6 * x3_1 / 2^64 := rfl
  have b_x15_3 : x15_3 < 2^64 := by omega
  have d_x15_3 : x15_2 + 2^64 * x15_3 = x6 * x3_1 := by omega
  clear e_x15_2 e_x15_3
  clear_value x15_3
  have e_x12_3 : x12_3 = (x12_2 + 0 + c_8) % 2^64 := rfl
  have e_c_9 : c_9 = (x12_2 + 0 + c_8) / 2^64 := rfl
  have l_x12_3 : x12_3 + 2^64 * c_9 = x12_2 + 0 + c_8 := by omega
  have b_x12_3 : x12_3 < 2^64 := by omega
  have b_c_9 : c_9 ≤ 1 := by omega
  clear e_x12_3 e_c_9
  clear_value s_7 x12_3 c_9
  have e_x13_3 : x13_3 = (x13_2 + x17_2 + c_9) % 2^64 := rfl
  have e_c_10 : c_10 = (x13_2 + x17_2 + c_9) / 2^64 := rfl
  have l_x13_3 : x13_3 + 2^64 * c_10 = x13_2 + x17_2 + c_9 := by omega
  have b_x13_3 : x13_3 < 2^64 := by omega
  have b_c_10 : c_10 ≤ 1 := by omega
  clear e_x13_3 e_c_10
  clear_value s_8 x13_3 c_10
  have e_x17_3 : x17_3 = x3_1 / 2^2 := rfl
  have b_x17_3 : x17_3 < 2^62 := by omega
  have sh_x17_3 : x17_2 + 2^64 * x17_3 = x3_1 * 2^62 := by omega
  clear e_x17_2 e_x17_3
  clear_value x17_3
  have e_x9_1 : x9_1 = (0 + 0 + c_10) % 2^64 := rfl
  have b_x9_1 : x9_1 < 2^64 := by omega
  obtain ⟨k_x9_1, b_k_x9_1, l_x9_1⟩ :
      ∃ k, k ≤ 1 ∧ x9_1 + 2^64 * k = 0 + 0 + c_10 :=
    ⟨(0 + 0 + c_10) / 2^64, by omega, by omega⟩
  clear e_x9_1
  clear_value x9_1
  have e_x10_2 : x10_2 = (x11_3 + x14_1 + 0) % 2^64 := rfl
  have e_c_11 : c_11 = (x11_3 + x14_1 + 0) / 2^64 := rfl
  have l_x10_2 : x10_2 + 2^64 * c_11 = x11_3 + x14_1 + 0 := by omega
  have b_x10_2 : x10_2 < 2^64 := by omega
  have b_c_11 : c_11 ≤ 1 := by omega
  clear e_x10_2 e_c_11
  clear_value s_9 x10_2 c_11
  have e_x11_4 : x11_4 = (x12_3 + x15_3 + c_11) % 2^64 := rfl
  have e_c_12 : c_12 = (x12_3 + x15_3 + c_11) / 2^64 := rfl
  have l_x11_4 : x11_4 + 2^64 * c_12 = x12_3 + x15_3 + c_11 := by omega
  have b_x11_4 : x11_4 < 2^64 := by omega
  have b_c_12 : c_12 ≤ 1 := by omega
  clear e_x11_4 e_c_12
  clear_value s_10 x11_4 c_12
  have e_x12_4 : x12_4 = (x13_3 + 0 + c_12) % 2^64 := rfl
  have e_c_13 : c_13 = (x13_3 + 0 + c_12) / 2^64 := rfl
  have l_x12_4 : x12_4 + 2^64 * c_13 = x13_3 + 0 + c_12 := by omega
  have b_x12_4 : x12_4 < 2^64 := by omega
  have b_c_13 : c_13 ≤ 1 := by omega
  clear e_x12_4 e_c_13
  clear_value s_11 x12_4 c_13
  have e_x3_2 : x3_2 = x4 * x10_2 % 2^64 := rfl
  have b_x3_2 : x3_2 < 2^64 := by omega
  clear_value x3_2
  have e_x13_4 : x13_4 = (x9_1 + x17_3 + c_13) % 2^64 := rfl
  have b_x13_4 : x13_4 < 2^64 := by omega
  obtain ⟨k_x13_4, b_k_x13_4, l_x13_4⟩ :
      ∃ k, k ≤ 1 ∧ x13_4 + 2^64 * k = x9_1 + x17_3 + c_13 :=
    ⟨(x9_1 + x17_3 + c_13) / 2^64, by omega, by omega⟩
  clear e_x13_4
  clear_value x13_4
  -- BEGIN round 1
  -- Cancellation: the low limb of `x10_1 + p0 * x3_1` is zero, so `x10_1 + lo_x14_1` is
  -- `0` or `2^64`, and `subs xzr, x10_1, #1` set the carry exactly when it is `2^64`.
  have hc_1 : x10_1 + lo_x14_1 = 2^64 * c_7 := by
    have h := cancel_low x10_1 inv modulus.l0 hinv
    rw [← e_x5, ← e_x4, ← e_x3_1, ← d_x14_1, Nat.add_mul_mod_self_left,
      Nat.mod_eq_of_lt b_lo_x14_1] at h
    clear * - h b_x10_1 b_lo_x14_1 l_c_7
    omega
  -- Neither `adc` wraps: the fifth limb is at most `1`, and the shifted quotient is below
  -- `2^62`.
  have hk_1 : k_x9_1 = 0 ∧ k_x13_4 = 0 := by
    clear * - l_x9_1 b_c_10 l_x13_4 b_x17_3 b_c_13
    omega
  -- The round invariant is a linear combination of the instruction equations.
  have I_1 : 2^64 * (x10_2 + 2^64 * x11_4 + 2^128 * x12_4 + 2^192 * x13_4)
      = (x10_1 + 2^64 * x11_2 + 2^128 * x12_2 + 2^192 * x13_2)
        + (x5 * x3_1 + 2^64 * (x6 * x3_1) + 2^254 * x3_1) := by
    clear * - hc_1 d_x14_1 d_x15_3 l_x11_3 l_x12_3 l_x13_3 l_x10_2 l_x11_4 l_x12_4 sh_x17_3 l_x9_1
        l_x13_4 hk_1
    omega
  clear * - ht hm hshape hinv hinv_lt e_x4 e_x5 e_x6 b_x4 b_x5 b_x6 e_x10 e_x11 e_x12 e_x13 I_0 I_1
      b_x10_2 b_x11_4 b_x12_4 b_x13_4 b_x3 b_x3_1 b_x3_2 e_x3_2
  -- END round 1
  have e_x15_4 : x15_4 = x6 * x3_2 % 2^64 := rfl
  have b_x15_4 : x15_4 < 2^64 := by omega
  clear_value x15_4
  have e_x17_4 : x17_4 = x3_2 * 2^62 % 2^64 := rfl
  have b_x17_4 : x17_4 < 2^64 := by omega
  clear_value x17_4
  have e_c_14 : c_14 = (x10_2 + 2^64 - 1 - (1 - 1)) / 2^64 := rfl
  have l_c_14 : (c_14 = 1 ∧ 1 + 1 ≤ x10_2 + 1) ∨ (c_14 = 0 ∧ x10_2 + 1 < 1 + 1) := by
    omega
  clear e_c_14
  clear_value c_14
  have p_x14_2 : x5 * x3_2 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x5 b_x3_2) (by norm_num)
  have e_x14_2 : x14_2 = x5 * x3_2 / 2^64 := rfl
  have b_x14_2 : x14_2 < 2^64 := by omega
  obtain ⟨lo_x14_2, b_lo_x14_2, d_x14_2⟩ :
      ∃ lo, lo < 2^64 ∧ lo + 2^64 * x14_2 = x5 * x3_2 :=
    ⟨x5 * x3_2 % 2^64, by omega, by omega⟩
  clear e_x14_2
  clear_value x14_2
  have e_x11_5 : x11_5 = (x11_4 + x15_4 + c_14) % 2^64 := rfl
  have e_c_15 : c_15 = (x11_4 + x15_4 + c_14) / 2^64 := rfl
  have l_x11_5 : x11_5 + 2^64 * c_15 = x11_4 + x15_4 + c_14 := by omega
  have b_x11_5 : x11_5 < 2^64 := by omega
  have b_c_15 : c_15 ≤ 1 := by omega
  clear e_x11_5 e_c_15
  clear_value s_12 x11_5 c_15
  have p_x15_5 : x6 * x3_2 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x6 b_x3_2) (by norm_num)
  have e_x15_5 : x15_5 = x6 * x3_2 / 2^64 := rfl
  have b_x15_5 : x15_5 < 2^64 := by omega
  have d_x15_5 : x15_4 + 2^64 * x15_5 = x6 * x3_2 := by omega
  clear e_x15_4 e_x15_5
  clear_value x15_5
  have e_x12_5 : x12_5 = (x12_4 + 0 + c_15) % 2^64 := rfl
  have e_c_16 : c_16 = (x12_4 + 0 + c_15) / 2^64 := rfl
  have l_x12_5 : x12_5 + 2^64 * c_16 = x12_4 + 0 + c_15 := by omega
  have b_x12_5 : x12_5 < 2^64 := by omega
  have b_c_16 : c_16 ≤ 1 := by omega
  clear e_x12_5 e_c_16
  clear_value s_13 x12_5 c_16
  have e_x13_5 : x13_5 = (x13_4 + x17_4 + c_16) % 2^64 := rfl
  have e_c_17 : c_17 = (x13_4 + x17_4 + c_16) / 2^64 := rfl
  have l_x13_5 : x13_5 + 2^64 * c_17 = x13_4 + x17_4 + c_16 := by omega
  have b_x13_5 : x13_5 < 2^64 := by omega
  have b_c_17 : c_17 ≤ 1 := by omega
  clear e_x13_5 e_c_17
  clear_value s_14 x13_5 c_17
  have e_x17_5 : x17_5 = x3_2 / 2^2 := rfl
  have b_x17_5 : x17_5 < 2^62 := by omega
  have sh_x17_5 : x17_4 + 2^64 * x17_5 = x3_2 * 2^62 := by omega
  clear e_x17_4 e_x17_5
  clear_value x17_5
  have e_x9_2 : x9_2 = (0 + 0 + c_17) % 2^64 := rfl
  have b_x9_2 : x9_2 < 2^64 := by omega
  obtain ⟨k_x9_2, b_k_x9_2, l_x9_2⟩ :
      ∃ k, k ≤ 1 ∧ x9_2 + 2^64 * k = 0 + 0 + c_17 :=
    ⟨(0 + 0 + c_17) / 2^64, by omega, by omega⟩
  clear e_x9_2
  clear_value x9_2
  have e_x10_3 : x10_3 = (x11_5 + x14_2 + 0) % 2^64 := rfl
  have e_c_18 : c_18 = (x11_5 + x14_2 + 0) / 2^64 := rfl
  have l_x10_3 : x10_3 + 2^64 * c_18 = x11_5 + x14_2 + 0 := by omega
  have b_x10_3 : x10_3 < 2^64 := by omega
  have b_c_18 : c_18 ≤ 1 := by omega
  clear e_x10_3 e_c_18
  clear_value s_15 x10_3 c_18
  have e_x11_6 : x11_6 = (x12_5 + x15_5 + c_18) % 2^64 := rfl
  have e_c_19 : c_19 = (x12_5 + x15_5 + c_18) / 2^64 := rfl
  have l_x11_6 : x11_6 + 2^64 * c_19 = x12_5 + x15_5 + c_18 := by omega
  have b_x11_6 : x11_6 < 2^64 := by omega
  have b_c_19 : c_19 ≤ 1 := by omega
  clear e_x11_6 e_c_19
  clear_value s_16 x11_6 c_19
  have e_x12_6 : x12_6 = (x13_5 + 0 + c_19) % 2^64 := rfl
  have e_c_20 : c_20 = (x13_5 + 0 + c_19) / 2^64 := rfl
  have l_x12_6 : x12_6 + 2^64 * c_20 = x13_5 + 0 + c_19 := by omega
  have b_x12_6 : x12_6 < 2^64 := by omega
  have b_c_20 : c_20 ≤ 1 := by omega
  clear e_x12_6 e_c_20
  clear_value s_17 x12_6 c_20
  have e_x3_3 : x3_3 = x4 * x10_3 % 2^64 := rfl
  have b_x3_3 : x3_3 < 2^64 := by omega
  clear_value x3_3
  have e_x13_6 : x13_6 = (x9_2 + x17_5 + c_20) % 2^64 := rfl
  have b_x13_6 : x13_6 < 2^64 := by omega
  obtain ⟨k_x13_6, b_k_x13_6, l_x13_6⟩ :
      ∃ k, k ≤ 1 ∧ x13_6 + 2^64 * k = x9_2 + x17_5 + c_20 :=
    ⟨(x9_2 + x17_5 + c_20) / 2^64, by omega, by omega⟩
  clear e_x13_6
  clear_value x13_6
  -- BEGIN round 2
  -- Cancellation: the low limb of `x10_2 + p0 * x3_2` is zero, so `x10_2 + lo_x14_2` is
  -- `0` or `2^64`, and `subs xzr, x10_2, #1` set the carry exactly when it is `2^64`.
  have hc_2 : x10_2 + lo_x14_2 = 2^64 * c_14 := by
    have h := cancel_low x10_2 inv modulus.l0 hinv
    rw [← e_x5, ← e_x4, ← e_x3_2, ← d_x14_2, Nat.add_mul_mod_self_left,
      Nat.mod_eq_of_lt b_lo_x14_2] at h
    clear * - h b_x10_2 b_lo_x14_2 l_c_14
    omega
  -- Neither `adc` wraps: the fifth limb is at most `1`, and the shifted quotient is below
  -- `2^62`.
  have hk_2 : k_x9_2 = 0 ∧ k_x13_6 = 0 := by
    clear * - l_x9_2 b_c_17 l_x13_6 b_x17_5 b_c_20
    omega
  -- The round invariant is a linear combination of the instruction equations.
  have I_2 : 2^64 * (x10_3 + 2^64 * x11_6 + 2^128 * x12_6 + 2^192 * x13_6)
      = (x10_2 + 2^64 * x11_4 + 2^128 * x12_4 + 2^192 * x13_4)
        + (x5 * x3_2 + 2^64 * (x6 * x3_2) + 2^254 * x3_2) := by
    clear * - hc_2 d_x14_2 d_x15_5 l_x11_5 l_x12_5 l_x13_5 l_x10_3 l_x11_6 l_x12_6 sh_x17_5 l_x9_2
        l_x13_6 hk_2
    omega
  clear * - ht hm hshape hinv hinv_lt e_x4 e_x5 e_x6 b_x4 b_x5 b_x6 e_x10 e_x11 e_x12 e_x13 I_0 I_1
      I_2 b_x10_3 b_x11_6 b_x12_6 b_x13_6 b_x3 b_x3_1 b_x3_2 b_x3_3 e_x3_3
  -- END round 2
  have e_x15_6 : x15_6 = x6 * x3_3 % 2^64 := rfl
  have b_x15_6 : x15_6 < 2^64 := by omega
  clear_value x15_6
  have e_x17_6 : x17_6 = x3_3 * 2^62 % 2^64 := rfl
  have b_x17_6 : x17_6 < 2^64 := by omega
  clear_value x17_6
  have e_c_21 : c_21 = (x10_3 + 2^64 - 1 - (1 - 1)) / 2^64 := rfl
  have l_c_21 : (c_21 = 1 ∧ 1 + 1 ≤ x10_3 + 1) ∨ (c_21 = 0 ∧ x10_3 + 1 < 1 + 1) := by
    omega
  clear e_c_21
  clear_value c_21
  have p_x14_3 : x5 * x3_3 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x5 b_x3_3) (by norm_num)
  have e_x14_3 : x14_3 = x5 * x3_3 / 2^64 := rfl
  have b_x14_3 : x14_3 < 2^64 := by omega
  obtain ⟨lo_x14_3, b_lo_x14_3, d_x14_3⟩ :
      ∃ lo, lo < 2^64 ∧ lo + 2^64 * x14_3 = x5 * x3_3 :=
    ⟨x5 * x3_3 % 2^64, by omega, by omega⟩
  clear e_x14_3
  clear_value x14_3
  have e_x11_7 : x11_7 = (x11_6 + x15_6 + c_21) % 2^64 := rfl
  have e_c_22 : c_22 = (x11_6 + x15_6 + c_21) / 2^64 := rfl
  have l_x11_7 : x11_7 + 2^64 * c_22 = x11_6 + x15_6 + c_21 := by omega
  have b_x11_7 : x11_7 < 2^64 := by omega
  have b_c_22 : c_22 ≤ 1 := by omega
  clear e_x11_7 e_c_22
  clear_value s_18 x11_7 c_22
  have p_x15_7 : x6 * x3_3 < 2^128 :=
    lt_of_lt_of_eq (Nat.mul_lt_mul'' b_x6 b_x3_3) (by norm_num)
  have e_x15_7 : x15_7 = x6 * x3_3 / 2^64 := rfl
  have b_x15_7 : x15_7 < 2^64 := by omega
  have d_x15_7 : x15_6 + 2^64 * x15_7 = x6 * x3_3 := by omega
  clear e_x15_6 e_x15_7
  clear_value x15_7
  have e_x12_7 : x12_7 = (x12_6 + 0 + c_22) % 2^64 := rfl
  have e_c_23 : c_23 = (x12_6 + 0 + c_22) / 2^64 := rfl
  have l_x12_7 : x12_7 + 2^64 * c_23 = x12_6 + 0 + c_22 := by omega
  have b_x12_7 : x12_7 < 2^64 := by omega
  have b_c_23 : c_23 ≤ 1 := by omega
  clear e_x12_7 e_c_23
  clear_value s_19 x12_7 c_23
  have e_x13_7 : x13_7 = (x13_6 + x17_6 + c_23) % 2^64 := rfl
  have e_c_24 : c_24 = (x13_6 + x17_6 + c_23) / 2^64 := rfl
  have l_x13_7 : x13_7 + 2^64 * c_24 = x13_6 + x17_6 + c_23 := by omega
  have b_x13_7 : x13_7 < 2^64 := by omega
  have b_c_24 : c_24 ≤ 1 := by omega
  clear e_x13_7 e_c_24
  clear_value s_20 x13_7 c_24
  have e_x17_7 : x17_7 = x3_3 / 2^2 := rfl
  have b_x17_7 : x17_7 < 2^62 := by omega
  have sh_x17_7 : x17_6 + 2^64 * x17_7 = x3_3 * 2^62 := by omega
  clear e_x17_6 e_x17_7
  clear_value x17_7
  have e_x9_3 : x9_3 = (0 + 0 + c_24) % 2^64 := rfl
  have b_x9_3 : x9_3 < 2^64 := by omega
  obtain ⟨k_x9_3, b_k_x9_3, l_x9_3⟩ :
      ∃ k, k ≤ 1 ∧ x9_3 + 2^64 * k = 0 + 0 + c_24 :=
    ⟨(0 + 0 + c_24) / 2^64, by omega, by omega⟩
  clear e_x9_3
  clear_value x9_3
  have e_x10_4 : x10_4 = (x11_7 + x14_3 + 0) % 2^64 := rfl
  have e_c_25 : c_25 = (x11_7 + x14_3 + 0) / 2^64 := rfl
  have l_x10_4 : x10_4 + 2^64 * c_25 = x11_7 + x14_3 + 0 := by omega
  have b_x10_4 : x10_4 < 2^64 := by omega
  have b_c_25 : c_25 ≤ 1 := by omega
  clear e_x10_4 e_c_25
  clear_value s_21 x10_4 c_25
  have e_x11_8 : x11_8 = (x12_7 + x15_7 + c_25) % 2^64 := rfl
  have e_c_26 : c_26 = (x12_7 + x15_7 + c_25) / 2^64 := rfl
  have l_x11_8 : x11_8 + 2^64 * c_26 = x12_7 + x15_7 + c_25 := by omega
  have b_x11_8 : x11_8 < 2^64 := by omega
  have b_c_26 : c_26 ≤ 1 := by omega
  clear e_x11_8 e_c_26
  clear_value s_22 x11_8 c_26
  have e_x12_8 : x12_8 = (x13_7 + 0 + c_26) % 2^64 := rfl
  have e_c_27 : c_27 = (x13_7 + 0 + c_26) / 2^64 := rfl
  have l_x12_8 : x12_8 + 2^64 * c_27 = x13_7 + 0 + c_26 := by omega
  have b_x12_8 : x12_8 < 2^64 := by omega
  have b_c_27 : c_27 ≤ 1 := by omega
  clear e_x12_8 e_c_27
  clear_value s_23 x12_8 c_27
  have e_x13_8 : x13_8 = (x9_3 + x17_7 + c_27) % 2^64 := rfl
  have b_x13_8 : x13_8 < 2^64 := by omega
  obtain ⟨k_x13_8, b_k_x13_8, l_x13_8⟩ :
      ∃ k, k ≤ 1 ∧ x13_8 + 2^64 * k = x9_3 + x17_7 + c_27 :=
    ⟨(x9_3 + x17_7 + c_27) / 2^64, by omega, by omega⟩
  clear e_x13_8
  clear_value x13_8
  -- BEGIN round 3
  -- Cancellation: the low limb of `x10_3 + p0 * x3_3` is zero, so `x10_3 + lo_x14_3` is
  -- `0` or `2^64`, and `subs xzr, x10_3, #1` set the carry exactly when it is `2^64`.
  have hc_3 : x10_3 + lo_x14_3 = 2^64 * c_21 := by
    have h := cancel_low x10_3 inv modulus.l0 hinv
    rw [← e_x5, ← e_x4, ← e_x3_3, ← d_x14_3, Nat.add_mul_mod_self_left,
      Nat.mod_eq_of_lt b_lo_x14_3] at h
    clear * - h b_x10_3 b_lo_x14_3 l_c_21
    omega
  -- Neither `adc` wraps: the fifth limb is at most `1`, and the shifted quotient is below
  -- `2^62`.
  have hk_3 : k_x9_3 = 0 ∧ k_x13_8 = 0 := by
    clear * - l_x9_3 b_c_24 l_x13_8 b_x17_7 b_c_27
    omega
  -- The round invariant is a linear combination of the instruction equations.
  have I_3 : 2^64 * (x10_4 + 2^64 * x11_8 + 2^128 * x12_8 + 2^192 * x13_8)
      = (x10_3 + 2^64 * x11_6 + 2^128 * x12_6 + 2^192 * x13_6)
        + (x5 * x3_3 + 2^64 * (x6 * x3_3) + 2^254 * x3_3) := by
    clear * - hc_3 d_x14_3 d_x15_7 l_x11_7 l_x12_7 l_x13_7 l_x10_4 l_x11_8 l_x12_8 sh_x17_7 l_x9_3
        l_x13_8 hk_3
    omega
  clear * - ht hm hshape hinv hinv_lt e_x4 e_x5 e_x6 b_x4 b_x5 b_x6 e_x10 e_x11 e_x12 e_x13 I_0 I_1
      I_2 I_3 b_x10_4 b_x11_8 b_x12_8 b_x13_8 b_x3 b_x3_1 b_x3_2 b_x3_3
  -- END round 3
  -- BEGIN conclusion
  subst e_x5 e_x6
  refine ⟨⟨b_x10_4, b_x11_8, b_x12_8, b_x13_8⟩, x3 + 2^64 * x3_1 + 2^128 * x3_2 + 2^192 * x3_3,
    by clear * - b_x3 b_x3_1 b_x3_2 b_x3_3; omega, ?_⟩
  -- `Q * p`, with the modulus in the shape the code assumes, as the sum of the four rounds'
  -- contributions.
  have hQp : (x3 + 2^64 * x3_1 + 2^128 * x3_2 + 2^192 * x3_3) * modulus.toNat
      = (modulus.l0 * x3 + 2^64 * (modulus.l1 * x3) + 2^254 * x3)
        + 2^64 * (modulus.l0 * x3_1 + 2^64 * (modulus.l1 * x3_1) + 2^254 * x3_1)
        + 2^128 * (modulus.l0 * x3_2 + 2^64 * (modulus.l1 * x3_2) + 2^254 * x3_2)
        + 2^192 * (modulus.l0 * x3_3 + 2^64 * (modulus.l1 * x3_3) + 2^254 * x3_3) := by
    simp only [Limbs.toNat, hshape.1, hshape.2]; ring
  simp only [Limbs.toNat] at hQp ⊢
  clear * - I_0 I_1 I_2 I_3 hQp e_x10 e_x11 e_x12 e_x13
  omega
  -- END conclusion

end CompElliptic.Asm.AArch64
